import json
import re
import os

# Updated descriptions dictionary (Items 1 - 122)
DESCRIPTIONS = {
    "aprons": "Designed to bring both practicality and style to everyday kitchen routines, this apron helps keep your outfit protected while you cook, bake, or prepare meals. Its comfortable design makes it easy to wear for longer periods, while the clean appearance adds a polished touch to your kitchen essentials. A useful blend of function and everyday convenience.",
    "bathmats": "Add comfort and character to your bathroom with a thoughtfully designed bathmat that creates a softer landing after every shower. Its practical surface helps keep the surrounding floor area cleaner and more comfortable, while its understated appearance blends easily with different bathroom interiors. A simple everyday essential that combines functionality, comfort, and decorative appeal.",
    "bedcover": "Give your bedroom an instant refresh with an elegant bedcover designed to add warmth, texture, and visual appeal. Draped neatly across the bed, it creates a more finished and inviting look while complementing your existing décor. Ideal for everyday styling or special occasions, it brings together comfort, practicality, and timeless bedroom elegance.",
    "bedsheet": "Create a fresh and inviting bedroom with a beautifully styled bedsheet designed for everyday comfort. Its versatile appearance allows it to complement both contemporary and traditional interiors, while the smooth presentation adds a refined touch to your bedding setup. Perfect for refreshing your room effortlessly, it combines everyday usability with understated elegance.",
    "blanket": "Wrap yourself in warmth and comfort with a cozy blanket designed for relaxing evenings and restful nights. Its versatile design makes it suitable for bedrooms, living spaces, or simply keeping close during cooler weather. Easy to style with existing interiors, it adds a comforting layer of warmth while maintaining a neat and inviting appearance.",
    "blinds": "Bring privacy, light control, and refined style to your interiors with these versatile blinds. Designed to complement modern living spaces, they help create a more comfortable atmosphere while adding structure to windows. Their clean appearance works beautifully across bedrooms, living rooms, and workspaces, making them a practical décor element that enhances both functionality and visual appeal.",
    "blinds-with-decor": "Transform ordinary windows into stylish focal points with decorative blinds that combine practical window coverage with an elevated aesthetic. Designed to complement your interior décor, they can add softness, structure, and personality to the room. Ideal for living rooms, bedrooms, and curated spaces, these blinds bring together everyday functionality and decorative sophistication.",
    "carpets": "Add warmth, texture, and personality to your interiors with a beautifully designed carpet. Whether placed in the living room, bedroom, or another thoughtfully styled space, it helps define the area while creating a more welcoming atmosphere. Its decorative presence can effortlessly complement existing furniture and décor, making everyday spaces feel more comfortable and complete.",
    "comforter-set": "Create a cozy and coordinated bedroom with a thoughtfully styled comforter set designed to bring comfort and visual harmony together. The coordinated appearance makes bed styling effortless while adding softness and warmth to your space. Ideal for everyday use, it gives your bedroom a polished, inviting look without requiring complicated décor changes.",
    "curtains": "Frame your windows beautifully with curtains that add softness, privacy, and character to your interiors. Their versatile styling makes them suitable for bedrooms, living rooms, and other spaces where atmosphere matters. Beyond covering windows, they help complete the room’s overall look by adding visual depth, warmth, and a more thoughtfully finished interior.",
    "cushions": "Add an effortless layer of comfort and personality with decorative cushions designed to enhance sofas, beds, chairs, and lounge spaces. Their versatile styling makes it easy to refresh an interior without changing major furniture pieces. Whether used individually or layered together, they bring softness, texture, and a polished decorative touch to everyday spaces.",
    "fridge-covers": "Give your kitchen a cleaner and more coordinated appearance with a stylish fridge cover designed to add a decorative layer around your refrigerator. It helps protect the surface from everyday dust and marks while introducing visual character to the kitchen. A practical décor accessory for keeping one of the busiest areas of your home looking organized.",
    "fridge-cover": "Give your kitchen a cleaner and more coordinated appearance with a stylish fridge cover designed to add a decorative layer around your refrigerator. It helps protect the surface from everyday dust and marks while introducing visual character to the kitchen. A practical décor accessory for keeping one of the busiest areas of your home looking organized.",
    "jute-placemat": "Bring a natural, earthy touch to your dining table with a jute-inspired placemat designed for everyday table styling. Its textured appearance creates warmth and visual interest while helping define each place setting. Perfect for casual meals, family gatherings, or relaxed entertaining, it combines practical table protection with a charming, organic-inspired aesthetic.",
    "kitchen-ware": "Make everyday cooking and serving more organized with thoughtfully selected kitchenware designed around practical use. From preparation to presentation, these essentials help bring convenience into your daily routine while keeping your kitchen visually coordinated. Their functional nature makes them useful for everyday households, while their clean presentation allows them to fit naturally into modern kitchen spaces.",
    "mattresses": "Create a more comfortable foundation for restful nights with a thoughtfully designed mattress made to support your everyday sleeping routine. Its presence can transform the overall feel of your bedroom while complementing your existing bedding. Designed around comfort and practicality, it is an essential bedroom piece for creating a more inviting and relaxing sleep environment.",
    "mattress": "Create a more comfortable foundation for restful nights with a thoughtfully designed mattress made to support your everyday sleeping routine. Its presence can transform the overall feel of your bedroom while complementing your existing bedding. Designed around comfort and practicality, it is an essential bedroom piece for creating a more inviting and relaxing sleep environment.",
    "napkin-set": "Complete your dining table with a coordinated napkin set that adds an elegant finishing touch to every meal. Whether used for everyday dining or special gatherings, these napkins help create a more polished table setting. Their versatile styling pairs easily with different tableware and décor, making them a practical yet decorative addition to your dining essentials.",
    "pillows": "Add another layer of comfort to your bedroom or lounge with thoughtfully designed pillows that combine softness and decorative appeal. Perfect for beds, sofas, or reading corners, they help create a more relaxed and inviting environment. Their versatile character makes them easy to coordinate with different interiors while adding subtle texture and visual depth.",
    "placemats-napkins": "Create a beautifully coordinated dining experience with a matching combination of placemats and napkins. Together, they help organize each place setting while adding texture, color, and visual harmony to the table. Suitable for everyday meals or entertaining guests, this pairing brings practical protection and decorative sophistication together in one easy table-setting solution.",
    "round-placemat": "Add a softer, more organic shape to your dining arrangement with a round placemat designed to frame individual place settings beautifully. It helps protect the table surface while creating a visually balanced foundation for plates and tableware. Ideal for casual dining or elegant gatherings, it adds a subtle decorative detail without overwhelming the overall table design.",
    "runners": "Elevate your dining or living space with a decorative runner that adds length, texture, and visual structure to the surface. Perfect for dining tables, consoles, or other furniture, it creates an easy styling layer that brings the surrounding décor together. A simple addition that can instantly make an everyday arrangement feel more thoughtfully curated.",
    "shower-curtains": "Refresh your bathroom with a shower curtain that adds privacy while contributing to the overall décor. Its decorative presence can help introduce personality and visual coordination to an otherwise functional space. Easy to incorporate into different bathroom styles, it offers a practical solution for everyday use while helping create a cleaner and more finished atmosphere.",
    "soap-dispenser-set": "Bring a more organized and coordinated look to your bathroom or wash area with a stylish soap dispenser set. Designed to keep everyday essentials neatly arranged, it combines practical convenience with decorative appeal. The coordinated presentation makes countertops feel more polished, helping transform simple daily routines into a cleaner and more thoughtfully styled experience.",
    "table-cover": "Protect and refresh your dining table with a beautifully styled table cover that combines practicality with decorative charm. It creates an easy foundation for everyday meals while helping introduce color, pattern, or texture into the room. Whether used daily or for gatherings, it helps your dining area feel cleaner, warmer, and more inviting.",
    "throws": "Add a cozy finishing layer to sofas, beds, or lounge chairs with a versatile throw designed for comfort and effortless styling. Perfect for relaxed evenings or decorative layering, it introduces warmth and texture without overwhelming the room. Fold it neatly or drape it casually to create an inviting atmosphere with minimal effort.",
    "turbie-towel": "Make post-shower hair care more convenient with a turbie towel designed to wrap comfortably around wet hair. Its practical shape helps keep hair neatly secured while you continue with your routine, making it especially useful after bathing. Compact and easy to use, it brings everyday convenience to your personal care essentials without unnecessary fuss.",
    "anti-skid-rubber-mat": "Add an extra layer of everyday safety and practicality with an anti-skid rubber mat designed for areas where stable footing matters. Its functional surface helps provide better grip while also protecting the floor beneath. Suitable for entrances, kitchens, bathrooms, or utility areas, it combines practical performance with a simple design that fits naturally into everyday spaces.",
    "artificial-flowers": "Bring the beauty of floral décor into your home without the need for constant maintenance. These artificial flowers add color, softness, and natural-inspired character to tables, shelves, consoles, and corners. Easy to style throughout the year, they create a welcoming atmosphere while offering a long-lasting decorative solution for homes, offices, and thoughtfully curated interiors.",
    "bonsai-jade-plant": "Introduce a touch of greenery and calm into your interior with a beautifully styled Jade Plant bonsai. Its compact form makes it ideal for desks, shelves, side tables, and decorative corners. Inspired by the timeless appeal of bonsai arrangements, it adds a refined natural element to your surroundings while requiring minimal styling effort.",
    "buddha": "Create a peaceful and balanced atmosphere with a Buddha statue designed to bring a sense of calm into your surroundings. Its detailed presence makes it suitable for living rooms, meditation spaces, entrances, or decorative corners. Whether displayed alone or paired with complementary accents, it adds a serene focal point to thoughtfully styled interiors.",
    "customised-wall-paper": "Give your walls a more personal identity with customised wallpaper created around your preferred style and visual theme. It can transform an ordinary wall into an expressive feature while complementing the surrounding furniture and décor. Ideal for bedrooms, living rooms, offices, or creative spaces, it offers a flexible way to create interiors that feel distinctly yours.",
    "doormat": "Make a welcoming first impression with a stylish doormat designed for everyday entrances. Its practical surface helps trap dirt and dust while adding decorative character to your doorway. With its attractive design and useful functionality, it works beautifully at home entrances, helping create a cleaner entryway while adding warmth and personality to the first step inside.",
    "floral-panels": "Add a dramatic botanical touch to your interiors with decorative floral panels designed to create visual impact. Their detailed floral character can transform plain walls and spaces into expressive decorative features. Ideal for bedrooms, living areas, event spaces, or creative corners, they bring depth, color, and a nature-inspired aesthetic into your surroundings.",
    "flower-vases": "Showcase your favorite flowers and botanical arrangements with an elegant vase designed to complement the beauty of the display. Whether filled with fresh blooms, artificial flowers, or used on its own, it adds height and character to tables, shelves, and consoles. A versatile décor piece that turns simple arrangements into thoughtful interior accents.",
    "flowers-bouquet": "Brighten your surroundings with a decorative flower bouquet designed to bring color and floral charm into everyday spaces. Perfect for tables, consoles, gifting, or special occasions, it creates an inviting visual focal point without requiring complicated styling. Its versatile presentation makes it easy to introduce a fresh, cheerful atmosphere into both modern and traditional interiors.",
    "jaguar": "Make a bold decorative statement with a striking jaguar-inspired showpiece designed for interiors that appreciate character and strong visual accents. Its sculptural presence makes it ideal for consoles, shelves, side tables, or display units. Whether styled individually or paired with complementary décor, it adds a confident focal point and a sense of artistic personality.",
    "laughing-buddha": "Invite a cheerful and welcoming presence into your space with a beautifully styled Laughing Buddha décor piece. Its expressive design makes it an eye-catching addition to shelves, consoles, entrances, or living areas. Whether chosen as a decorative accent or a meaningful gift, it brings warmth, personality, and a positive visual energy to the surroundings.",
    "leafy-hangings": "Add an effortless botanical element to your interiors with decorative leafy hangings designed to bring texture and movement to walls or vertical spaces. Their nature-inspired appearance works beautifully in living rooms, balconies, bedrooms, and creative corners. Easy to style alongside existing décor, they introduce greenery-inspired charm without requiring the upkeep of real plants.",
    "metal-tree": "Create a striking decorative focal point with a sculptural metal tree designed to bring artistic structure into your interior. Its branching form adds visual interest to consoles, shelves, side tables, or display areas. Combining nature-inspired shapes with contemporary decorative character, it works especially well in spaces where you want a distinctive accent without excessive ornamentation.",
    "mirror": "Enhance your interiors with a decorative mirror that combines everyday usefulness with visual appeal. Strategically placed, it can reflect light and create a greater sense of openness while adding an elegant focal point to the room. Suitable for bedrooms, living spaces, entryways, or dressing areas, it blends naturally with a variety of interior styles.",
    "show-piece": "Add personality to your interiors with a carefully designed showpiece that works as a standalone decorative accent. Ideal for shelves, consoles, side tables, or display cabinets, it can help fill spaces while creating a thoughtful focal point. Its decorative character makes it suitable for both contemporary homes and interiors that favor more classic styling.",
    "show-pieces": "Create a more layered and expressive interior with decorative show pieces selected to add character and visual interest. Display them individually or combine different pieces to create a curated arrangement across shelves, consoles, and tables. They provide an easy way to personalize your surroundings while adding decorative depth and a sense of thoughtful styling.",
    "wall-art": "Turn an empty wall into a visual focal point with expressive wall art designed to add character to your interiors. Whether displayed in a living room, bedroom, hallway, or workspace, it can help define the atmosphere of the room. A versatile décor element for introducing personality, visual balance, and an artistic finishing touch.",
    "wall-clock": "Keep track of time while adding a decorative focal point to your wall with a stylish wall clock. Beyond its everyday function, its design can complement furniture, artwork, and surrounding décor. Ideal for living rooms, bedrooms, offices, and hallways, it brings together practicality and visual structure in a simple yet effective interior accent.",
    "wall-painting": "Give your interiors an expressive finishing touch with a decorative wall painting designed to add color, depth, and personality. It can become a central visual element above sofas, beds, consoles, or dining spaces. Whether your décor is contemporary or classic, a thoughtfully selected painting can transform an ordinary wall into a more memorable part of the room.",
    "jaguar-showpiece": "Make a confident statement with a jaguar showpiece designed to add sculptural character to your décor. Its bold silhouette makes it suitable for consoles, shelves, office desks, display units, or statement corners. Used on its own or alongside other accents, it creates an artistic focal point that brings personality and a sophisticated edge to the room.",
    "botanical-printed-blinds": "Introduce nature-inspired character to your windows with botanical printed blinds that combine visual beauty with everyday functionality. Their leafy and floral-inspired patterns can soften interiors while adding personality to otherwise simple window spaces. Ideal for bedrooms, living rooms, and creative corners, they offer an easy way to bring decorative detail and natural-inspired charm indoors.",
    "elegant-runners": "Add a refined finishing layer to dining tables, consoles, or furniture surfaces with an elegant runner designed to enhance the surrounding décor. Its elongated format creates visual structure while adding texture and sophistication. Perfect for everyday styling or entertaining, it provides a simple way to make your space feel more coordinated, polished, and thoughtfully decorated.",
    "crystal-candle-holders": "Create an elegant glow with crystal-inspired candle holders designed to turn ordinary candlelight into a decorative experience. Their reflective appearance can add sparkle and sophistication to dining tables, consoles, sideboards, or special occasions. Whether displayed individually or arranged together, they bring a refined decorative layer that works beautifully across modern and classic interiors.",
    "customised-wall-paper-floral-design": "Transform your walls with a customised floral wallpaper design that brings softness, color, and botanical character into your interiors. Created to suit your preferred visual direction, it can become a statement feature behind beds, sofas, desks, or dining spaces. An expressive décor solution for adding personality while creating a more immersive and visually engaging environment.",
    "customised-wall-paper-buddha-design": "Create a distinctive and calming interior feature with customised wallpaper inspired by Buddha imagery. Designed to add visual depth and a peaceful character, it can transform a plain wall into a meaningful decorative statement. Suitable for living spaces, meditation corners, bedrooms, or reception areas, it combines personalised styling with a serene artistic presence.",
    "elegant-diaries": "Keep ideas, plans, notes, and everyday thoughts beautifully organised with an elegant diary designed for both personal and professional use. Its refined appearance makes it suitable for desks, meetings, journaling, or gifting. More than a writing essential, it adds a polished touch to everyday routines while encouraging a more intentional and organised approach to your day.",
    "candle-holders": "Create a warm and inviting atmosphere with decorative candle holders designed to complement your interior styling. Perfect for dining tables, shelves, consoles, bedside tables, or special occasions, they provide an elegant way to display candles while adding visual structure. Style them individually or in groups to create a cozy arrangement with a refined decorative finish.",
    "elegant-doormat": "Make your entrance feel more welcoming with an elegant doormat that combines practical everyday use with decorative appeal. Designed to help trap dirt and dust while enhancing the doorway, it adds a polished first impression to your home. Its refined appearance makes it especially suitable for entrances where functionality and interior styling need to work together.",
    "fountains": "Bring movement and tranquility into your interiors with a decorative fountain designed to create a calming focal point. The flowing-water-inspired element can add atmosphere to living rooms, entrances, balconies, or peaceful corners. Its decorative presence introduces a sense of relaxation and visual interest, making it an appealing accent for spaces designed around comfort and serenity.",
    "ceramic-storage-jars-set": "Keep everyday essentials organized while adding decorative charm with a coordinated set of ceramic storage jars. Ideal for kitchens, dining spaces, shelves, or countertops, they combine useful storage with an attractive presentation. Their coordinated appearance helps reduce visual clutter while adding a refined accent to spaces where organization and interior styling need to work together.",
    "laughing-buddha-statue": "Add a warm and cheerful decorative presence to your home with a Laughing Buddha statue designed to create an inviting focal point. Its expressive form works beautifully on consoles, shelves, entryways, or living spaces. Whether selected for personal décor or gifting, it brings visual warmth and a distinctive character to thoughtfully arranged interiors.",
    "show-piece-vintage-wall-decor": "Bring old-world character to your walls with a vintage-inspired decorative showpiece designed to create an artistic focal point. Its classic visual appeal works beautifully in living rooms, hallways, studies, or curated corners. Ideal for interiors that appreciate timeless details, it adds personality and a sense of history without making the overall space feel overly traditional.",
    "feng-shui-turtle": "Introduce a meaningful decorative accent with a Feng Shui-inspired turtle designed to add character to your home or workspace. Its distinctive form makes it suitable for desks, shelves, consoles, and display areas. Beyond its decorative appeal, the turtle-inspired symbolism makes it a thoughtful choice for gifting or creating a more intentional and balanced interior.",
    "wall-art-metal-discs": "Create a bold contemporary wall arrangement with decorative metal discs designed to add texture, dimension, and visual rhythm. Their sculptural appearance works beautifully across feature walls, living rooms, hallways, and reception spaces. Arranged individually or as a composition, they transform plain surfaces into artistic focal points while bringing a modern decorative character to the room.",
    "wall-art-led-wall-clock": "Combine everyday timekeeping with decorative lighting through an LED wall clock designed to become a functional feature on your wall. Its illuminated appearance adds visual impact while keeping the time easy to notice. Suitable for bedrooms, living rooms, offices, or modern interiors, it brings together technology-inspired styling and practical everyday functionality.",
    "vintage-wall-clock": "Add timeless character to your interiors with a vintage-inspired wall clock designed to combine function with classic decorative appeal. Its distinctive styling can become a focal point in living rooms, studies, dining areas, or hallways. More than a timekeeping essential, it brings personality and an old-world visual touch to thoughtfully designed spaces.",
    "combo-10-cork-executive-essentials": "Bring practical elegance to professional gifting with a thoughtfully curated cork executive essentials set. Designed for workspaces and everyday routines, it combines useful desk accessories with the distinctive character of cork. A refined choice for corporate occasions, employee gifting, client appreciation, or personal use, it offers a balanced blend of functionality, sustainability-inspired styling, and professional presentation.",
    "combo-11-cork-signature-desk-set": "Create a polished workspace with the Cork Signature Desk Set, thoughtfully assembled around everyday desk essentials. Its cork-based character brings a natural visual warmth to professional environments while keeping the overall presentation refined. Suitable for corporate gifting, onboarding, celebrations, or personal workspaces, it makes everyday organization feel more intentional and stylish.",
    "combo-12-cork-traveller-set": "Designed for people who carry their work and essentials wherever they go, the Cork Traveller Set combines portability with practical style. Its cork-inspired design gives the collection a distinctive natural character while remaining suitable for professional use. A thoughtful gifting option for employees, clients, travellers, or anyone who appreciates organized essentials on the move.",
    "combo-13-cork-desk-grow-set": "Bring together productivity and greenery with the Cork Desk & Grow Set, designed to add useful desk essentials alongside a touch of nature. Its combination makes it especially suitable for modern workspaces where functionality and personality matter. A thoughtful corporate gift for employees, clients, or teams, it creates a more inviting and inspiring desk environment.",
    "combo-14-cork-hosting-set": "Designed for thoughtful hosts and polished everyday gatherings, the Cork Hosting Set combines useful essentials with the distinctive character of cork. Its presentation makes it suitable for corporate gifting, festive occasions, housewarming moments, or personal use. A versatile collection that adds warmth and practical charm while making gifting feel more considered and memorable.",
    "combo-29-cork-diary-pen-set": "Bring everyday writing essentials together in a refined cork diary and pen set designed for work, planning, and personal notes. The combination offers a practical gifting solution with a natural, professional appearance. Suitable for employees, clients, students, or colleagues, it makes an understated yet useful gift that fits easily into both professional and personal routines.",
    "combo-30-cork-printed-diary-pen-set": "Add personality to everyday writing with a printed cork diary and pen combination designed for organized notes and creative ideas. Its distinctive appearance makes it suitable for corporate gifting, events, employee appreciation, or personal use. Practical and easy to carry, the set turns simple writing essentials into a more thoughtful and visually appealing gift.",
    "combo-36-cork-workstation-set": "Upgrade the everyday desk experience with a Cork Workstation Set designed around organization and practical workspace essentials. Its natural cork-inspired appearance adds warmth to professional environments while maintaining a polished presentation. Ideal for corporate gifting and office use, it brings useful functionality together with a distinctive design suited to modern workspaces.",
    "combo-37-cork-desk-travel-set": "Designed for professionals who move between desks and destinations, the Cork Desk & Travel Set brings useful essentials together in one versatile collection. Its cork-inspired finish adds natural character while keeping the overall presentation refined. A practical choice for corporate gifting, employee rewards, travel occasions, or anyone who values organized everyday essentials.",
    "combo-44-cork-premium-desk-collection": "Make a sophisticated statement with the Cork Premium Desk Collection, designed to elevate everyday workspace essentials. Its coordinated presentation and natural cork character make it especially suitable for premium corporate gifting. Ideal for clients, senior professionals, employee recognition, or special occasions, it combines practical desk functionality with a refined and thoughtfully curated appearance.",
    "combo-45-cork-lenia-laptop-set": "Designed around modern professional routines, the Cork Lenia Laptop Set combines practical laptop-focused essentials with the distinctive look of cork. Its polished presentation makes it a suitable choice for corporate gifting, work-from-anywhere professionals, and everyday office use. Functional and refined, it adds a more organized and natural touch to the modern work setup.",
    "combo-18-executive-laptop-set-ocean-mist": "Bring a polished sense of style to professional travel with the Executive Laptop Set in Ocean Mist. Designed around modern laptop users, it combines practical essentials with a sophisticated color character. Suitable for corporate gifting, employee rewards, or professional occasions, it offers a useful everyday collection with a contemporary appearance that travels effortlessly between office and workspaces.",
    "combo-19-executive-laptop-set-deep-blue": "Designed for professionals who value practical organization with a refined appearance, the Executive Laptop Set in Deep Blue brings together useful laptop-focused essentials. Its rich color character gives the collection a confident professional feel, making it suitable for corporate gifting, client appreciation, employee recognition, or everyday work. A practical set with a polished presentation.",
    "combo-20-executive-laptop-set-brown": "The Executive Laptop Set in Brown combines practical laptop essentials with a warm, sophisticated visual character. Designed for professional routines, it makes an appropriate choice for corporate gifting, business occasions, or personal work use. Its coordinated presentation creates a polished impression while helping keep important everyday work essentials organized and ready to carry.",
    "combo-46-cork-printed-hosting-set": "Bring personality to hosting and gifting with the Cork Printed Hosting Set, combining useful essentials with distinctive printed cork styling. Its natural-inspired character makes it suitable for festive occasions, corporate gifts, housewarming moments, or everyday hosting. A thoughtful collection that blends practical utility with an expressive presentation, making the simple act of gifting feel more personal.",
    "combo-47-cork-bark-hosting-set": "Inspired by the natural character of cork bark, this hosting set brings earthy visual appeal to practical everyday essentials. Its distinctive texture-inspired styling makes it a thoughtful choice for corporate gifting, celebrations, housewarmings, or personal hosting. Designed to feel both useful and special, it adds a natural warmth to gifting and entertaining occasions.",
    "box-print-planter-cork-table-top-planter": "Add a touch of greenery to your desk or tabletop with a Box Print cork planter designed for compact indoor styling. Its distinctive printed appearance gives the planter a decorative identity while keeping the presentation natural and contemporary. Ideal for small plants, workspaces, shelves, or gifting, it brings together greenery and thoughtful design in one compact accent.",
    "bohemian-print-planter-cork-table-top-planter": "Introduce relaxed, artistic character to your workspace or home with the Bohemian Print cork tabletop planter. Its expressive pattern adds visual interest while providing a stylish home for small plants. Perfect for desks, shelves, side tables, or gifting, it combines nature-inspired décor with a distinctive design that works beautifully in modern and eclectic interiors.",
    "diamond-planter-cork-table-top-planter": "Add geometric character to your tabletop with the Diamond cork planter, designed to showcase small plants in a stylish and compact form. Its diamond-inspired appearance creates visual structure while the cork character adds warmth. Ideal for desks, shelves, workspaces, or gifting, it offers a simple way to combine greenery with contemporary decorative styling.",
    "feather-planter-cork-table-top-planter": "Bring a light, nature-inspired touch to your interiors with the Feather cork tabletop planter. Designed for small plants, it combines a distinctive feather-inspired print with the warm character of cork. Ideal for desks, shelves, bedside tables, or gifting, it creates a charming decorative accent that makes greenery feel more personal and thoughtfully styled.",
    "olive-planter-cork-table-top-planter": "Create a natural and understated tabletop display with the Olive cork planter, designed to complement small plants and greenery. Its olive-inspired character brings a subtle botanical feel while the cork finish adds warmth to the presentation. Perfect for desks, shelves, and gifting, it offers an easy way to introduce greenery into everyday surroundings.",
    "chocochip-planter-cork-table-top-planter": "Add playful character to your plant décor with the Chocochip cork tabletop planter. Its distinctive print creates visual interest while providing a compact home for small plants or succulents. Suitable for desks, shelves, side tables, and gifting, it combines natural-inspired cork styling with a fun design that brings personality into everyday spaces.",
    "cork-belly-coaster": "Protect your tabletop while adding a natural decorative touch with the Cork Belly Coaster. Designed for everyday drinks, it provides a practical surface between your glass or cup and the furniture beneath. Its cork character makes it a simple yet stylish addition to dining tables, work desks, coffee tables, or thoughtful gift collections.",
    "cork-leaf-shape-coaster": "Bring botanical-inspired style to everyday table settings with a leaf-shaped cork coaster designed to protect surfaces from drink marks. Its distinctive silhouette adds decorative personality while maintaining practical functionality. Ideal for home, office, cafés, or gifting, it turns a simple tabletop essential into a charming accent that blends naturally with modern and organic-inspired décor.",
    "cork-diamond-uv-print-coaster": "Add a geometric decorative detail to your table with a Diamond UV Print cork coaster designed for everyday use. Its printed surface brings visual character while the cork construction provides a practical base for cups and glasses. Suitable for desks, dining tables, or gifting, it combines useful surface protection with contemporary, design-led styling.",
    "cork-box-print-coaster": "Keep your tabletops protected while adding a distinctive design accent with the Cork Box Print Coaster. Its printed appearance gives the simple coaster a more curated look, making it suitable for home, office, or gifting. A practical everyday essential that combines cork’s natural character with a visually interesting printed finish.",
    "cork-coaster-with-stand": "Keep your coasters neatly organized with this cork coaster set featuring a dedicated stand for convenient storage. Designed to make everyday table settings more practical, it keeps coasters together when not in use while adding a natural decorative touch. Suitable for homes, offices, cafés, and gifting, it combines organization with understated style.",
    "cork-olive-square-trivet": "Protect your dining or kitchen surfaces from warm cookware with a practical Cork Olive Square Trivet. Its square format provides a stable decorative base while the olive-inspired styling adds visual warmth. Designed for everyday use, it works beautifully on dining tables and kitchen counters while also making a useful addition to thoughtful gifting collections.",
    "diaries": "Capture ideas, plans, notes, and everyday thoughts in a thoughtfully designed diary made for writing on the go. Suitable for professional schedules, journaling, meetings, study, or personal planning, it combines practical usefulness with a polished presentation. An easy gifting choice for colleagues, clients, students, or anyone who enjoys keeping their thoughts organized.",
    "pen": "A reliable pen is an everyday essential, and this thoughtfully presented piece is designed to fit naturally into work, study, and personal routines. Easy to carry and useful across different occasions, it makes a simple yet practical gift. Pair it with a diary or gifting set to create a more complete writing experience.",
    "photo-frames": "Turn meaningful memories into decorative displays with an elegant photo frame designed to complement your home or workspace. Perfect for photographs, special moments, or gifting, it helps transform personal memories into visible décor. Place it on desks, shelves, bedside tables, or consoles to create a warm and personal accent within your surroundings.",
    "candles": "Add warmth, personality, and visual charm to your interiors with decorative candles designed to be enjoyed as both décor and ambient accents. Their artistic presentation makes them suitable for shelves, tables, bedside corners, celebrations, and gifting. Whether displayed unlit or glowing softly, they create an inviting atmosphere while adding a distinctive finishing detail.",
    "decorative-candles": "Enrich your home's ambiance with our Exclusive Décor Collection. Each piece is designed to infuse warmth, character, and beauty into your space. From elegant accents to artistic creations, our décor range helps you express your unique style effortlessly.",
    "pastel-blue-bowl-candle": "Bring a soft and calming touch to your décor with this hand-poured Pastel Blue Bowl Candle. Its bowl-inspired shape and gentle color make it a beautiful decorative accent for bedside tables, consoles, coffee tables, or gifting. Whether enjoyed as ambient décor or saved for special moments, it adds a subtle sense of warmth and tranquility.",
    "orange-pumpkin-bowl-candle": "Celebrate cozy seasonal styling with this hand-poured Orange Pumpkin Bowl Candle, designed to combine playful form with decorative warmth. Its pumpkin-inspired silhouette makes it especially charming for festive displays, autumn-inspired décor, gifting, or cozy corners. A visually distinctive candle that adds warmth and character even before it is lit.",
    "ocean-bowl-candle": "Bring a calming coastal mood into your space with the Ocean Bowl Candle, hand-poured to create a decorative centerpiece inspired by the beauty of the sea. Its bowl-shaped presentation makes it ideal for tables, shelves, or gifting. A soothing accent for relaxed interiors, it combines artistic candle design with an inviting sense of tranquility.",
    "pumpkin-boat-candle": "Add playful seasonal character to your décor with the Pumpkin Boat Candle, a hand-poured piece designed to stand out as a decorative accent. Its distinctive shape makes it suitable for festive arrangements, gifting, shelves, or tables. Whether displayed alone or paired with other candles, it creates a warm and charming visual centerpiece.",
    "green-succulent-jar-candle": "Bring the calming look of greenery into your space with this Green Succulent Jar Candle. Its succulent-inspired design combines the appearance of a miniature botanical arrangement with the warmth of candle décor. Ideal for desks, bedside tables, shelves, or gifting, it creates a charming decorative accent for plant lovers and cozy interior spaces.",
    "blue-love-jar-candle": "Add a romantic touch to special moments with the Blue Love Jar Candle, designed to combine expressive styling with warm candlelight. Its charming presentation makes it suitable for gifting, anniversaries, date nights, or personal décor. A thoughtful decorative piece that adds softness and personality to bedside tables, shelves, celebrations, and intimate spaces.",
    "bubble-jar-candle": "Make your candle display more playful with the Bubble Jar Candle, featuring a distinctive bubbly form that creates visual texture. Its artistic appearance makes it suitable for modern interiors, bedside styling, shelves, or gifting. Whether displayed as a centerpiece or enjoyed for its warm glow, it adds personality to spaces that appreciate unique décor.",
    "peony-boat-candle": "Bring floral elegance to your décor with the Peony Boat Candle, a hand-poured piece inspired by the delicate beauty of peony flowers. Its boat-shaped presentation creates an artistic focal point for tables, shelves, celebrations, or gifting. Designed to feel decorative even when unlit, it adds softness, romance, and a handcrafted character to your surroundings.",
    "hearty-gel-wax-jar-candle": "Create a warm and expressive atmosphere with the Hearty Gel Wax Jar Candle, designed around a charming heart-inspired aesthetic. Its clear gel-wax presentation adds visual depth while making it an attractive decorative accent. Ideal for gifting, romantic occasions, bedrooms, or cozy corners, it combines heartfelt design with the inviting glow of candlelight.",
    "3-shade-flower-jar-candle": "Bring colorful floral character to your interiors with the 3-Shade Flower Jar Candle. Its layered flower-inspired design creates an eye-catching presentation, making it suitable for shelves, bedside tables, celebrations, or gifting. A decorative piece that blends multiple tones with handcrafted candle artistry, adding a cheerful and elegant touch to your surroundings.",
    "ocean-jar-candle": "Create a calming coastal-inspired atmosphere with the Ocean Jar Candle, designed to bring sea-inspired visual character into your décor. Its jar format makes it easy to display on tables, shelves, desks, or bedside corners. A thoughtful decorative choice for relaxed interiors, it combines artistic presentation with the warm ambience associated with candlelight.",
    "caffe-latte-jar-candle": "Bring café-inspired warmth into your décor with the Caffé Latte Jar Candle, designed with a cozy visual character reminiscent of a comforting coffee moment. Its jar presentation makes it easy to style across desks, bedside tables, shelves, and coffee corners. A charming choice for gifting or creating a warm, relaxed atmosphere at home.",
    "whipped-floral-jar-candle": "Add a soft and luxurious floral accent to your space with the Whipped Floral Jar Candle. Its whipped-style decorative presentation creates a delicate, dessert-inspired visual while floral details add charm. Ideal for gifting, bedrooms, dressing tables, or shelves, it works beautifully as a decorative piece that brings softness, personality, and handcrafted character into your surroundings.",
    "diamond-jar-candle-gift": "Designed to make gifting feel extra special, the Diamond Jar Candle combines a distinctive diamond-inspired presentation with the warmth of candle décor. Its elegant appearance makes it suitable for birthdays, celebrations, anniversaries, festive occasions, or thoughtful surprises. A decorative candle that feels personal and premium while adding a stylish touch to any space.",
    "matcha-latte-jar-candle": "Bring the calming aesthetic of a matcha café moment into your home with the Matcha Latte Jar Candle. Its soft, refreshing visual character makes it an appealing addition to desks, bedside tables, shelves, or cozy corners. Ideal for gifting or personal décor, it combines a contemporary beverage-inspired theme with the warmth and charm of candle styling.",
    "sunflower-jar-candle": "Brighten your surroundings with the cheerful Sunflower Jar Candle, designed around the uplifting beauty of sunflower-inspired décor. Its floral presentation makes it a charming addition to shelves, tables, bedrooms, or gifting collections. A thoughtful decorative candle for anyone who loves flowers, warm interiors, and handcrafted pieces that add a little brightness to everyday spaces.",
    "rose-garden-jar-candle": "Bring the romantic charm of a blooming rose garden into your décor with this beautifully styled jar candle. Its rose-inspired presentation creates an elegant focal point for bedrooms, dressing tables, shelves, or special occasions. Suitable for gifting or personal use, it adds softness, floral character, and a warm decorative presence to thoughtfully styled interiors.",
    "mini-floral-candle-bouquet": "Combine the charm of flowers with the warmth of handcrafted candle décor in this Mini Floral Candle Bouquet. Its bouquet-inspired arrangement makes it an especially thoughtful choice for birthdays, anniversaries, celebrations, or simple surprises. Decorative even when unlit, it offers a lasting floral-inspired presentation that brings color, personality, and warmth into any setting.",
    "royal-red-peony-candle": "Make a bold floral statement with the Royal Red Peony Candle, designed to capture the richness and elegance of a blooming peony. Its deep, expressive presentation makes it ideal for romantic décor, celebrations, gifting, or statement displays. A handcrafted accent that brings drama, warmth, and sophisticated floral character to tables, shelves, or special occasions.",
    "blushing-rose-candle-bouquet": "Add a romantic and delicate touch to gifting with the Blushing Rose Candle Bouquet. Designed to resemble a charming floral arrangement while serving as decorative candle art, it makes a memorable choice for anniversaries, birthdays, celebrations, or thoughtful surprises. Its soft floral character brings warmth and elegance while offering an alternative to traditional bouquets.",
    "3-rose-candle-bouquet": "Create a timeless floral-inspired gift with the 3-Rose Candle Bouquet, featuring three beautifully styled rose candles arranged like a decorative bouquet. Ideal for romantic occasions, birthdays, anniversaries, or special surprises, it combines the visual charm of roses with handcrafted candle artistry. A thoughtful keepsake-style gift that adds warmth and personality to any setting.",
    "tulip-sapphire-candle-bouquet": "Bring sophisticated floral character to your décor with the Tulip Sapphire Candle Bouquet. Inspired by the graceful form of tulips, its distinctive sapphire-inspired presentation makes it a striking decorative accent. Perfect for gifting, celebrations, or personal styling, it combines the elegance of a floral arrangement with the lasting decorative appeal of handcrafted candle art.",
    "white-chocolate-strawberry-jar-candle": "Add a playful dessert-inspired touch to your décor with the White Chocolate & Strawberry Jar Candle. Its sweet visual theme makes it an appealing gift for birthdays, celebrations, or anyone who enjoys charming decorative pieces. Styled like a delightful treat while functioning as candle décor, it brings warmth, personality, and a whimsical character to your space.",
    "floral-jar-candle-sachet-combo": "Combine decorative candle charm with a thoughtful gifting touch through this Floral Jar Candle and Sachet Combo. Its floral-inspired presentation creates an elegant visual while the accompanying sachet adds another layer to the experience. Ideal for celebrations, festive gifting, self-care moments, or thoughtful surprises, it offers a beautifully coordinated collection with a warm, handcrafted feel.",
    "red-mini-heart-jar-candle": "Add a small but expressive touch to special moments with the Red Mini Heart Jar Candle. Its heart-inspired design and rich red character make it especially suitable for romantic gifting, anniversaries, date nights, or festive occasions. Compact and decorative, it creates a warm accent while conveying a thoughtful sentiment through its charming presentation."
}

def normalize_slug(slug_or_name):
    s = slug_or_name.lower()
    s = re.sub(r'[\s_–—&]+', '-', s)
    s = re.sub(r'[^a-z0-9\-]', '', s)
    return s.strip('-')

# Update vinsho-commerce-seed.json
seed_path = "vinsho-commerce-seed.json"
if os.path.exists(seed_path):
    with open(seed_path, 'r', encoding='utf-8') as f:
        seed_data = json.load(f)
    
    updated_count = 0
    for product in seed_data.get('products', []):
        slug = normalize_slug(product.get('slug', ''))
        name_slug = normalize_slug(product.get('name', ''))
        
        matched_desc = DESCRIPTIONS.get(slug) or DESCRIPTIONS.get(name_slug)
        
        # Try fuzzy/substring matching for combo and special names if needed
        if not matched_desc:
            for key in DESCRIPTIONS:
                if key in slug or key in name_slug or slug in key or name_slug in key:
                    matched_desc = DESCRIPTIONS[key]
                    break
        
        if matched_desc:
            product['description'] = matched_desc
            product['descriptionSource'] = 'written'
            updated_count += 1
            
    with open(seed_path, 'w', encoding='utf-8') as f:
        json.dump(seed_data, f, indent=2, ensure_ascii=False)
    print(f"Updated {updated_count} products in {seed_path}")

# Update vinsho-content.json
content_path = "vinsho-content.json"
if os.path.exists(content_path):
    with open(content_path, 'r', encoding='utf-8') as f:
        content_data = json.load(f)
    
    updated_count = 0
    for product in content_data.get('products', []):
        slug = normalize_slug(product.get('slug', ''))
        name_slug = normalize_slug(product.get('name', ''))
        
        matched_desc = DESCRIPTIONS.get(slug) or DESCRIPTIONS.get(name_slug)
        if not matched_desc:
            for key in DESCRIPTIONS:
                if key in slug or key in name_slug or slug in key or name_slug in key:
                    matched_desc = DESCRIPTIONS[key]
                    break
        
        if matched_desc:
            product['description'] = matched_desc
            product['descriptionSource'] = 'written'
            updated_count += 1
            
    with open(content_path, 'w', encoding='utf-8') as f:
        json.dump(content_data, f, indent=2, ensure_ascii=False)
    print(f"Updated {updated_count} products in {content_path}")

# Update vinsho_products.json
vproducts_path = "vinsho_products.json"
if os.path.exists(vproducts_path):
    with open(vproducts_path, 'r', encoding='utf-8') as f:
        vproducts_data = json.load(f)
    
    updated_count = 0
    for product in vproducts_data:
        slug = normalize_slug(product.get('slug', ''))
        name_slug = normalize_slug(product.get('name', ''))
        
        matched_desc = DESCRIPTIONS.get(slug) or DESCRIPTIONS.get(name_slug)
        if not matched_desc:
            for key in DESCRIPTIONS:
                if key in slug or key in name_slug or slug in key or name_slug in key:
                    matched_desc = DESCRIPTIONS[key]
                    break
        
        if matched_desc:
            product['description'] = matched_desc
            updated_count += 1
            
    with open(vproducts_path, 'w', encoding='utf-8') as f:
        json.dump(vproducts_data, f, indent=2, ensure_ascii=False)
    print(f"Updated {updated_count} products in {vproducts_path}")

# Update candles.json
candles_path = "src/data/products/candles.json"
if os.path.exists(candles_path):
    with open(candles_path, 'r', encoding='utf-8') as f:
        candles_data = json.load(f)
    
    updated_count = 0
    for product in candles_data:
        slug = normalize_slug(product.get('slug', ''))
        name_slug = normalize_slug(product.get('name', ''))
        
        matched_desc = DESCRIPTIONS.get(slug) or DESCRIPTIONS.get(name_slug)
        if not matched_desc:
            for key in DESCRIPTIONS:
                if key in slug or key in name_slug or slug in key or name_slug in key:
                    matched_desc = DESCRIPTIONS[key]
                    break
        
        if matched_desc:
            product['description'] = matched_desc
            updated_count += 1
            
    with open(candles_path, 'w', encoding='utf-8') as f:
        json.dump(candles_data, f, indent=2, ensure_ascii=False)
    print(f"Updated {updated_count} products in {candles_path}")
